name: Flake8 Workflow
run-name: Flake8 Workflow
on:
  workflow_call:
    inputs:
      python-version:
        type: string
        default: '3.8'

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python  
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Run flake8
        run: |
          python -m flake8 .
