name: Pytest Workflow
run-name: Pytest Workflow
on:
  workflow_call:
    inputs:
      python-version:
        type: string
        default: '3.8'

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python  
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Test with pytest
        run: |
            pip install pytest
            pytest .
